python makeplot.py -f UL_v2 -S "noSyst" -y 2018 -s --lep "electron" -C "Top_TvsQCD_nominal>0.6 && (N_muLoose_nominal+N_elLoose_nominal)==0 " -p #--lumi --mertree --merpart
python makeplot.py -f UL_v2 -S "noSyst" -y 2018 -s --lep "electron" -C "Top_TvsQCD_nominal>0.6 && top_region_nominal==0 && Fwd4_region_nominal==0 && AK8_region_nominal==0 && FatJet_M_nominal>=100 && FatJet_M_nominal<=140 && (N_muLoose_nominal+N_elLoose_nominal)==0" -p
python makeplot.py -f UL_v2 -S "noSyst" -y 2018 -s --lep "electron" -C "Top_TvsQCD_nominal>0.6 && top_region_nominal==1 && Fwd4_region_nominal==0 && AK8_region_nominal==0 && FatJet_M_nominal>=100 && FatJet_M_nominal<=140 && (N_muLoose_nominal+N_elLoose_nominal)==0" -p
python makeplot.py -f UL_v2 -S "noSyst" -y 2018 -s --lep "electron" -C "Top_TvsQCD_nominal>0.6 && top_region_nominal==0 && Fwd4_region_nominal==1 && AK8_region_nominal==0 && FatJet_M_nominal>=100 && FatJet_M_nominal<=140 && (N_muLoose_nominal+N_elLoose_nominal)==0" -p
python makeplot.py -f UL_v2 -S "noSyst" -y 2018 -s --lep "electron" -C "Top_TvsQCD_nominal>0.6 && top_region_nominal==1 && Fwd4_region_nominal==1 && AK8_region_nominal==0 && FatJet_M_nominal>=100 && FatJet_M_nominal<=140 && (N_muLoose_nominal+N_elLoose_nominal)==0" -p
python makeplot.py -f UL_v2 -S "noSyst" -y 2018 -s --lep "electron" -C "Top_TvsQCD_nominal>0.6 && top_region_nominal==0 && Fwd4_region_nominal==0 && AK8_region_nominal==1 && FatJet_M_nominal>=100 && FatJet_M_nominal<=140 && (N_muLoose_nominal+N_elLoose_nominal)==0" -p
python makeplot.py -f UL_v2 -S "noSyst" -y 2018 -s --lep "electron" -C "Top_TvsQCD_nominal>0.6 && top_region_nominal==1 && Fwd4_region_nominal==0 && AK8_region_nominal==1 && FatJet_M_nominal>=100 && FatJet_M_nominal<=140 && (N_muLoose_nominal+N_elLoose_nominal)==0" -p
python makeplot.py -f UL_v2 -S "noSyst" -y 2018 -s --lep "electron" -C "Top_TvsQCD_nominal>0.6 && top_region_nominal==0 && Fwd4_region_nominal==1 && AK8_region_nominal==1 && FatJet_M_nominal>=100 && FatJet_M_nominal<=140 && (N_muLoose_nominal+N_elLoose_nominal)==0" -p
python makeplot.py -f UL_v2 -S "noSyst" -y 2018 -s --lep "electron" -C "Top_TvsQCD_nominal>0.6 && top_region_nominal==1 && Fwd4_region_nominal==1 && AK8_region_nominal==1 && FatJet_M_nominal>=100 && FatJet_M_nominal<=140 && (N_muLoose_nominal+N_elLoose_nominal)==0" -p
python makeplot.py -f UL_v2 -S "noSyst" -y 2018 -s --lep "electron" -C "Top_TvsQCD_nominal>0.6 && top_region_nominal==0 && Fwd4_region_nominal==0 && AK8_region_nominal==2 && FatJet_M_nominal>=100 && FatJet_M_nominal<=140 && (N_muLoose_nominal+N_elLoose_nominal)==0" -p
python makeplot.py -f UL_v2 -S "noSyst" -y 2018 -s --lep "electron" -C "Top_TvsQCD_nominal>0.6 && top_region_nominal==1 && Fwd4_region_nominal==0 && AK8_region_nominal==2 && FatJet_M_nominal>=100 && FatJet_M_nominal<=140 && (N_muLoose_nominal+N_elLoose_nominal)==0" -p
python makeplot.py -f UL_v2 -S "noSyst" -y 2018 -s --lep "electron" -C "Top_TvsQCD_nominal>0.6 && top_region_nominal==0 && Fwd4_region_nominal==1 && AK8_region_nominal==2 && FatJet_M_nominal>=100 && FatJet_M_nominal<=140 && (N_muLoose_nominal+N_elLoose_nominal)==0" -p
python makeplot.py -f UL_v2 -S "noSyst" -y 2018 -s --lep "electron" -C "Top_TvsQCD_nominal>0.6 && top_region_nominal==1 && Fwd4_region_nominal==1 && AK8_region_nominal==2 && FatJet_M_nominal>=100 && FatJet_M_nominal<=140 && (N_muLoose_nominal+N_elLoose_nominal)==0" -p
python makeplot.py -f UL_v2 -S "noSyst" -y 2018 -s --lep "electron" -C "Top_TvsQCD_nominal>0.6 && top_region_nominal==0 && Fwd4_region_nominal==0 && AK8_region_nominal==0 && (FatJet_M_nominal<100 || FatJet_M_nominal>140) && (N_muLoose_nominal+N_elLoose_nominal)==0" -p
python makeplot.py -f UL_v2 -S "noSyst" -y 2018 -s --lep "electron" -C "Top_TvsQCD_nominal>0.6 && top_region_nominal==1 && Fwd4_region_nominal==0 && AK8_region_nominal==0 && (FatJet_M_nominal<100 || FatJet_M_nominal>140) && (N_muLoose_nominal+N_elLoose_nominal)==0" -p
python makeplot.py -f UL_v2 -S "noSyst" -y 2018 -s --lep "electron" -C "Top_TvsQCD_nominal>0.6 && top_region_nominal==0 && Fwd4_region_nominal==1 && AK8_region_nominal==0 && (FatJet_M_nominal<100 || FatJet_M_nominal>140) && (N_muLoose_nominal+N_elLoose_nominal)==0" -p
python makeplot.py -f UL_v2 -S "noSyst" -y 2018 -s --lep "electron" -C "Top_TvsQCD_nominal>0.6 && top_region_nominal==1 && Fwd4_region_nominal==1 && AK8_region_nominal==0 && (FatJet_M_nominal<100 || FatJet_M_nominal>140) && (N_muLoose_nominal+N_elLoose_nominal)==0" -p
python makeplot.py -f UL_v2 -S "noSyst" -y 2018 -s --lep "electron" -C "Top_TvsQCD_nominal>0.6 && top_region_nominal==0 && Fwd4_region_nominal==0 && AK8_region_nominal==1 && (FatJet_M_nominal<100 || FatJet_M_nominal>140) && (N_muLoose_nominal+N_elLoose_nominal)==0" -p
python makeplot.py -f UL_v2 -S "noSyst" -y 2018 -s --lep "electron" -C "Top_TvsQCD_nominal>0.6 && top_region_nominal==1 && Fwd4_region_nominal==0 && AK8_region_nominal==1 && (FatJet_M_nominal<100 || FatJet_M_nominal>140) && (N_muLoose_nominal+N_elLoose_nominal)==0" -p
python makeplot.py -f UL_v2 -S "noSyst" -y 2018 -s --lep "electron" -C "Top_TvsQCD_nominal>0.6 && top_region_nominal==0 && Fwd4_region_nominal==1 && AK8_region_nominal==1 && (FatJet_M_nominal<100 || FatJet_M_nominal>140) && (N_muLoose_nominal+N_elLoose_nominal)==0" -p
python makeplot.py -f UL_v2 -S "noSyst" -y 2018 -s --lep "electron" -C "Top_TvsQCD_nominal>0.6 && top_region_nominal==1 && Fwd4_region_nominal==1 && AK8_region_nominal==1 && (FatJet_M_nominal<100 || FatJet_M_nominal>140) && (N_muLoose_nominal+N_elLoose_nominal)==0" -p
python makeplot.py -f UL_v2 -S "noSyst" -y 2018 -s --lep "electron" -C "Top_TvsQCD_nominal>0.6 && top_region_nominal==0 && Fwd4_region_nominal==0 && AK8_region_nominal==2 && (FatJet_M_nominal<100 || FatJet_M_nominal>140) && (N_muLoose_nominal+N_elLoose_nominal)==0" -p
python makeplot.py -f UL_v2 -S "noSyst" -y 2018 -s --lep "electron" -C "Top_TvsQCD_nominal>0.6 && top_region_nominal==1 && Fwd4_region_nominal==0 && AK8_region_nominal==2 && (FatJet_M_nominal<100 || FatJet_M_nominal>140) && (N_muLoose_nominal+N_elLoose_nominal)==0" -p
python makeplot.py -f UL_v2 -S "noSyst" -y 2018 -s --lep "electron" -C "Top_TvsQCD_nominal>0.6 && top_region_nominal==0 && Fwd4_region_nominal==1 && AK8_region_nominal==2 && (FatJet_M_nominal<100 || FatJet_M_nominal>140) && (N_muLoose_nominal+N_elLoose_nominal)==0" -p
python makeplot.py -f UL_v2 -S "noSyst" -y 2018 -s --lep "electron" -C "Top_TvsQCD_nominal>0.6 && top_region_nominal==1 && Fwd4_region_nominal==1 && AK8_region_nominal==2 && (FatJet_M_nominal<100 || FatJet_M_nominal>140) && (N_muLoose_nominal+N_elLoose_nominal)==0" -p




