#python submit_condor_trig.py -d "DataMu_2016" -f "Trigger_v0" -t "BDT_Tprime"                   
#python submit_condor_trig.py -d "QCD_2016" -f "Trigger_v0" -t "BDT_Tprime"                      
#python submit_condor_trig.py -d "WJets_2016" -f "Trigger_v0" -t "BDT_Tprime"                    
#python submit_condor_trig.py -d "TT_Mtt_2016" -f "Trigger_v0" -t "BDT_Tprime"                   
#python submit_condor_trig.py -d "Tprime_LH_2016" -f "Trigger_v0" -t "BDT_Tprime"                
#python submit_condor_trig.py -d "ST_2016" -f "Trigger_v0" -t "BDT_Tprime" 

#python submit_condor_trig.py -d "DataMu_2017" -f "Trigger_v0" -t "BDT_Tprime"                   
#python submit_condor_trig.py -d "QCD_2017" -f "Trigger_v0" -t "BDT_Tprime"                      
#python submit_condor_trig.py -d "WJets_2017" -f "Trigger_v0" -t "BDT_Tprime"                    
#python submit_condor_trig.py -d "TT_Mtt_2017" -f "Trigger_v0" -t "BDT_Tprime"                   
#python submit_condor_trig.py -d "Tprime_LH_2017" -f "Trigger_v0" -t "BDT_Tprime"                
#python submit_condor_trig.py -d "ST_2017" -f "Trigger_v0" -t "BDT_Tprime" 
#python submit_condor_trig.py -d "DataEle_2017" -f "Trigger_v0" -t "BDT_Tprime"
#python submit_condor_trig.py -d "DataHTD_2017" -f "Trigger_v0" -t "BDT_Tprime"
#python submit_condor_trig.py -d "DataPh_2017" -f "Trigger_v0" -t "BDT_Tprime"

python submit_condor_trig.py -d "TT_Mtt_2018" -f "Trigger_v0" -t "BDT_Tprime"
python submit_condor_trig.py -d "DataMu_2018" -f "Trigger_v0" -t "BDT_Tprime" 
python submit_condor_trig.py -d "QCD_2018" -f "Trigger_v0" -t "BDT_Tprime" 
python submit_condor_trig.py -d "WJets_2018" -f "Trigger_v0" -t "BDT_Tprime"  
#python submit_condor_trig.py -d "Tprime_LH_2018" -f "Trigger_v0" -t "BDT_Tprime" 
python submit_condor_trig.py -d "ST_2018" -f "Trigger_v0" -t "BDT_Tprime" 
python submit_condor_trig.py -d "DataEle_2018" -f "Trigger_v0" -t "BDT_Tprime" 
python submit_condor_trig.py -d "DataHT_2018" -f "Trigger_v0" -t "BDT_Tprime" 

